#######################################################
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#░░░███████░░██░░░░░██░████████░░█████████░████████░░░#
#░░█████████░██░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░██░░░░░██░██░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░██░░░░░░░░██░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░██░░░░░░░░██░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░░███████░░██░░░░░██░████████░░███████░░░████████░░░#
#░░░░░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░░░░█████████░░#
#░░░░░░░░░██░██░░░░░██░██░░░░░░░░██░░░░░░░░██░░░░░██░░#
#░░██░░░░░██░███░░░███░██░░░░░░░░██░░░░░░░░██░░░░░██░░#
#░░█████████░█████████░██░░░░░░░░██░░░░░░░░██░░░░░██░░#
#░░░███████░░░███████░░██░░░░░░░░█████████░██░░░░░██░░#
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#░░█████████████████████████████████████████████████░░#
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#░░░███████░░██░░░░░██░░░░███░░░░░███████░░██░░░░░██░░#
#░░█████████░███░░░███░░░█████░░░█████████░██░░░░░██░░#
#░░██░░░░░██░████░████░░██░░░██░░██░░░░░██░██░░░░░██░░#
#░░██░░░░░░░░████░████░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░██░░░░░░░░██░███░██░██░░░░░██░██░░░░░░░░██░░░░░██░░#
#░░░███████░░██░███░██░█████████░░███████░░█████████░░#
#░░░░░░░░░██░██░░█░░██░██░░░░░██░░░░░░░░██░██░░░░░██░░#
#░░░░░░░░░██░██░░░░░██░██░░░░░██░░░░░░░░██░██░░░░░██░░#
#░░██░░░░░██░██░░░░░██░██░░░░░██░██░░░░░██░██░░░░░██░░#
#░░█████████░██░░░░░██░██░░░░░██░█████████░██░░░░░██░░#
#░░░███████░░██░░░░░██░██░░░░░██░░███████░░██░░░░░██░░#
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#░░█████████████████████████████████████████████████░░#
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#░░██░░░░░██░█████████░████████░░░███████░░█████████░░#
#░░██░░░░░██░██░░░░░░░░██░░░░░██░█████████░██░░░░░░░░░#
#░░██░░░░░██░██░░░░░░░░██░░░░░██░██░░░░░██░██░░░░░░░░░#
#░░██░░░░░██░██░░░░░░░░██░░░░░██░██░░░░░░░░██░░░░░░░░░#
#░░██░░░░░██░██░░░░░░░░██░░░░░██░██░░░░░░░░██░░░░░░░░░#
#░░██░░░░░██░███████░░░████████░░░███████░░█████████░░#
#░░██░░░░░██░██░░░░░░░░█████████░░░░░░░░██░██░░░░░░░░░#
#░░██░░░░░██░██░░░░░░░░██░░░░░██░░░░░░░░██░██░░░░░░░░░#
#░░░██░░░██░░██░░░░░░░░██░░░░░██░██░░░░░██░██░░░░░░░░░#
#░░░░█████░░░██░░░░░░░░██░░░░░██░█████████░██░░░░░░░░░#
#░░░░░███░░░░█████████░██░░░░░██░░███████░░█████████░░#
#░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░#
#######################################################

####################################################### 
#                                                     #
# Text For The Lobby Location Hologram.               #
#                                                     #
#######################################################                                                             
Lobby_Loc_Text: Lobby

#######################################################
#                                                     #
# Text For The Join Location Hologram                 #
#                                                     # 
#######################################################
Join_Loc_Text: Join Here!

#######################################################
#                                                     #
# Text For The Arena Stacker Origin Location          #
#                                                     #
#######################################################
Origin_Loc_Text: Arena Stacker

#######################################################
#                                                     #
# Player Can Be Within X Blocks Of The Join           #
# Location In Order To Be Detected And Added          #
# To The Game Queue.                                  #
#                                                     #
# Hard Minimum = 1 And Hard Maximum = 20              #
#                                                     #
#######################################################
Join_Distance: 4

#######################################################
#                                                     #
# The Size, In Blocks, By Which Every Arena           #
# Will Have Access To In Terms Of                     #
# X, Y, And Z - IE: 50x50x50.                         #
#                                                     #
# Hard Minimum = 30 And Hard Maximum = 100            #
#                                                     #
#######################################################
Arena_Max_Size: 50

#######################################################
#                                                     #
# The Number Of Arenas That Will Be Allowed           #
# To Run In Any Particular Instance Of Super          #
# Smash Verse.                                        #
#                                                     #
# Hard Minimum = 1 And Hard Maximum = 36              #
#                                                     #
#######################################################
Max_Arenas: 1

#######################################################
#                                                     #
# The Number Of Lives That All Players Will           #
# Start With At The Beginning Of Each Match           #
# For The Stock GameMode.                             #
#                                                     #
# Hard Minimum = 1 And Hard Maximum = 99              #
#                                                     #
#######################################################
Start_Lives: 3

#######################################################
#                                                     #
# The Amount Of Damage, In Percent, That All          #
# Players Will Start The Match, And Respawn           #
# With.                                               #
#                                                     #
# Hard Minimum = 0 And Hard Maximum = 999             #
#                                                     #
#######################################################
Start_Dmg: 0

#######################################################
#                                                     #
# The Amount Of Time, In Seconds, That                #
# Players Will Have To Wait Before The Match          #
# Starts Once They Have Been Teleported To            #
# The Arena.                                          #
#                                                     #
# Hard Minimum = 0 And Hard Maximum = 120             #
#                                                     #
#######################################################
CountDown_Seconds: 5

#######################################################
#                                                     #
# The Amount Of Time, In Seconds, That                #
# Players Will Have To Wait Before They Will          #
# Respawn After Being KOd.                            #
#                                                     #
# Hard Minimum = 0 And Hard Maximum = 30              # 
#                                                     #
#######################################################
Respawn_Seconds: 5

#######################################################
#                                                     #
# The Amount Of Damage, In Percent That               #
# All Players Will Start With During Sudden           #
# Death To Make For A Quick, Chaotic Finish           #
#                                                     #
# Hard Minimum = 300 And Hard Maximum = 999           #
#                                                     #
#######################################################
SuddenDeathStartDmg: 300

#######################################################
#                                                     #
# The Number Of Players Required For A Game To Start  #
#                                                     #
#######################################################
PlayersRequired: 4

#######################################################
#                                                     #
# The Speed By Which Arena Templates Are              #
# Constructed.                                        #
#                                                     #
# Please Adjust This Option To Tailor The             #
# Power Of Your Computer, Server Host, Or             #
# Dedicated Box.                                      #
#                                                     #
# Available Options:                                  #
# 5 = Server Killer = 1000 Blocks/Tick                #
# 4 = Fast          = 0500 Blocks/Tick                #
# 3 = Mediumm       = 0250 Blocks/Tick                #
# 2 = Slow          = 0100 Blocks/Tick                #
# 1 = Casual        = 0050 Blocks/Tick                #
#                                                     #
# NOTES:                                              #
#                                                     #
# 1.) If Your Server Still Lags On The                #
# Slow Setting, Then Something Else Is To             #
# Blame Or You Need To Upgrade Your Server            #
# Specs.                                              #
#                                                     #
# 2.) The Best Time To Use The Server Killer          #
# Arena Generation Speed Is When You Are Going        #
# To Run Only One Arena At A Time, Otherwise,         #
# Run A Slower Arena Generation Speed, Such As        #
# Casual.                                             #
#                                                     #
#######################################################
TemplateBuildSpeed: 5